merged GetArticle into GetText and fixes in lamdba_function.py to call the python functions
TheSentimentalists/SentimentalistsApp-Backend pull request #64
Opened 2020-10-22 19:19 UTC by ANA-POTJE

2020-10-22 19:34 UTC, jsjohnstone requested changes
Just one change around initialising the 'article' object :)

2020-10-22 19:34 UTC, jsjohnstone commented on src/getText.py
> +                 'header': '',
Wonder if we should standardise these to make it easier on the frontend, and instead return an error object like:
`{"error" : "The article could not be downloaded." }`

2020-10-22 19:34 UTC, jsjohnstone commented on src/getText.py
> +                 'header': '',
Maybe ignore this and it could be a future fix.

2020-10-22 19:34 UTC, jsjohnstone commented on src/lambda_function.py
> +        "article" : {},
I think we should actually remove this variable initialisation - it's created as part of the good or error case down below.

2020-10-23 10:54 UTC, jsjohnstone requested changes

2020-10-23 10:54 UTC, jsjohnstone commented on src/lambda_function.py
> +        object['results'].append({'type': 'polarity',     'error': 'no data available'})
We should standardise how objects/results are returned - it's slightly different between components.

2020-10-23 15:03 UTC, ANA-POTJE commented
Closing this PR, as changes requested will be available in the next version of this branch.

2020-10-23 15:04 UTC, closed without merging